only_aa_data = select_single_experiment_from_data_set_2(human_data_table,"approach_avoid");
get_bhat_dist_heat_map_comparing_rat_to_human(only_aa_data,rat_data_table,1, ...
    "heat map human to rat Comparison",version_name,1)
get_bhat_dist_heat_map_comparing_rat_to_human(only_aa_data,rat_data_table,0, ...
    "heat map human to rat Comparison",version_name,1)

colors = distinguishable_colors(30);
only_aa_data = select_single_experiment_from_data_set_2(human_data_table,"approach_avoid");

normalized_human_to_rat_comparison_single_plot("rat_reward_choice.xlsx", ...
    only_aa_data,"cluster_tables_for_rat_created_04_16_2024", ...
    "3d cluster plot rat to human comparison",colors,1)

normalized_human_to_rat_comparison_single_plot("rat_reward_choice.xlsx", ...
    only_aa_data,"cluster_tables_for_rat_created_04_16_2024", ...
    "3d cluster plot rat to human comparison",colors,0)