function fin_table = read_eye_csv_to_table(table_name)

opts = spreadsheetImportOptions('NumVariables',22,'VariableNamingRule',"preserve");
init_table = readtable(table_name,opts,'ReadVariableNames',true);
% minimal cleaning
new_table = removevars(init_table, "Var1");
new_table(1,:) = [];
new_table.Properties.VariableNames = {'index','subjectidnumber','tasktypedone',...
    'decision_made','real_r','real_c','left_pupil_diameter',...
    'left_x_coords','left_y_coords','added_q_len','end_of_reading','order','num_maxes',...
    'num_mins','decision_timing','big_ups','big_dips','avg_eng',...
    'eng_before_dec','eng_around_dec','eng_after_dec'};

pruned_table = prune_eye_tables(new_table);

first_convert = convertvars(pruned_table,{'index','subjectidnumber','tasktypedone',...
   'decision_made','real_r','real_c','added_q_len','end_of_reading',...
   'order','num_maxes','num_mins','decision_timing','big_ups', 'big_dips', 'avg_eng', ...
    'eng_before_dec', 'eng_around_dec', 'eng_after_dec'},'string');

% done in two steps because you can't convert directly from cell to double
fin_table = convertvars(first_convert, {'subjectidnumber','decision_made','real_r','real_c','added_q_len','end_of_reading',...
   'order','num_maxes','num_mins','decision_timing','big_ups', 'big_dips', 'avg_eng', ...
    'eng_before_dec', 'eng_around_dec', 'eng_after_dec'}, "double");

end